version: "3"
services:
  whitebox-api:
    image: whitebox-api
    container_name: whitebox-api
    volumes:
      - ./data:/data
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8080
    ports:
      - 8080:8080
